### ISSUE TITLE
Replicate changes back to MYSQL

### ISSUE THREAD

**Issue by ralphievolt** [perak/mysql-shadow#3]
I've been playing with this package since my boss wanted me to use the MySQL as our database but i'm not familiar with MySQL.. I followed usage procedure but got this error..

 Exception while invoking method '/Foil_Tank/insert' TypeError: Cannot read property 'skipFields' of undefined
I20150107-10:35:07.242(8)?     at Object.<anonymous> (packages/perak:mysql-shadow/mysql-shadow.js:315:1)
I20150107-10:35:07.242(8)?     at packages/matb33:collection-hooks/insert.js:27:1
I20150107-10:35:07.242(8)?     at Array.forEach (native)
I20150107-10:35:07.243(8)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
I20150107-10:35:07.243(8)?     at after (packages/matb33:collection-hooks/insert.js:26:1)
I20150107-10:35:07.243(8)?     at Object.CollectionHooks.defineAdvice.self (packages/matb33:collection-hooks/insert.js:40:1)
I20150107-10:35:07.243(8)?     at Object.collection.(anonymous function) [as insert] (packages/matb33:collection-hooks/collection-hooks.js:104:1)
I20150107-10:35:07.244(8)?     at [object Object].m.(anonymous function) (packages/mongo/collection.js:866:1)
I20150107-10:35:07.244(8)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1599:1)
I20150107-10:35:07.244(8)?     at packages/ddp/livedata_server.js:648:1

**Comment by perak** [comment]
Hi Ralph,

That's little bug in my package. To avoid error, please pass empty {} options object to MySQLShadowCollection:

```
MySQLShadowCollection(SomeCollection, connectionName, {});
```

**Comment by ralphievolt** [comment]
got it.. thanks
